### ISSUE TITLE
readme file is missing

### ISSUE THREAD

**Issue by shantanuo** [md-farhan-memon/redis_graph_demo#1]
Please add the readme file that will explain how to use the python script.

**Comment by md-farhan-memon** [comment]
Closing the issue as README added with details of the dataset and relevant commands.

**Comment by shantanuo** [comment]
I have imported the data successfully. 

```
2124 nodes created with label 'b'character''
438 nodes created with label 'b'house''
12 nodes created with label 'b'book''
3 nodes created with label 'b'writer''
14 relations created for type 'b'wrote''
2208 relations created for type 'b'belongs''
Construction of graph 'GOT_DEMO' complete: 2577 nodes created, 2222 relations created in 0.259813 seconds

```
But how do I use the data? Please add a few sample commands as well.

**Comment by md-farhan-memon** [comment]
@shantanuo added few query commands into readme along with screenshots.
